### ISSUE TITLE
Prijedlog poveznice na pravu sliku u README.md

### ISSUE THREAD

**Issue by sbravar** [e-radionicacom/Soldered-INA219-Current-Sensor-Arduino-Library#2]
https://github.com/SolderedElectronics/Soldered-INA219-Current-Sensor-Arduino-Library/blob/e78d4cc50298734c473f8000042cc864a887de41/README.md?plain=1#L7

umjesto:

https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg

čini mi se da bi moglo biti:

https://github.com/SolderedElectronics/Voltage---current-sensor-INA219-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333066.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
